src/MercadoLibre.AspNetCore.TestServer/Models/ErrorViewModel.cs
using System;

namespace MercadoLibre.AspNetCore.TestServer.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/MercadoLibre.AspNetCore.TestServer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MercadoLibre.AspNetCore.TestServer.Models;

namespace MercadoLibre.AspNetCore.TestServer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/MercadoLibre.AspNetCore.TestServer/Controllers/MercadoLibreController.cs
using MercadoLibre.AspNetCore.SDK;
using MercadoLibre.AspNetCore.SDK.Exceptions;
using MercadoLibre.AspNetCore.SDK.Resources;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MercadoLibre.AspNetCore.TestServer.Controllers
{
    [ApiController]
    [Route("ml")]
    public class MercadoLibreController : Controller
    {
        private static readonly Dictionary<long, SDK.Models.AuthorizeToken> _Tokens = new Dictionary<long, SDK.Models.AuthorizeToken>();

        private Meli Meli { get; }

        public MercadoLibreController(Meli meli)
        {
            Meli = meli;
        }

        [HttpGet("")]
        public async Task<IActionResult> Index()
        {
            return Redirect(Meli.GetAuthUrl(AuthUrls.MLB, "https://localhost:5001/ml/auth"));
        }

        [HttpGet("auth")]
        public async Task<IActionResult> Auth(string code)
        {
            try
            {
                await Meli.AuthorizeAsync(code, "https://localhost:5001/ml/auth");

                _Tokens[Meli.AuthorizeToken.UserId] = Meli.AuthorizeToken;

                return View(Meli.AuthorizeToken);
            }
            catch
            {
                return BadRequest();
            }
        }

        [HttpPost("auth")]
        public async Task<IActionResult> Refresh([FromForm] SDK.Models.AuthorizeToken token)
        {
            try
            {
                await Meli.RefreshTokenAsync(token.RefreshToken);

                _Tokens[Meli.AuthorizeToken.UserId] = Meli.AuthorizeToken;

                return View("Auth", Meli.AuthorizeToken);
            }
            catch
            {
                return BadRequest();
            }
        }

        [HttpGet("userInfo")]
        public async Task<IActionResult> UserInfo()
        {
            Meli.AuthorizeToken = _Tokens.Values.FirstOrDefault();

            var users = new UsersResource(Meli);
            var userInfo = await users.GetUserAsync();

            return View(userInfo);
        }

        [HttpGet("notifications")]
        public IActionResult Notifications()
        {
            return Ok();
        }
    }
}

src/MercadoLibre.AspNetCore.TestServer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/MercadoLibre.AspNetCore.TestServer/Views/MercadoLibre/Auth.cshtml
@model MercadoLibre.AspNetCore.SDK.Models.AuthorizeToken

@{
    ViewData["Title"] = "Authentication Result";
}

AccessToken: @Model.AccessToken
<br />
RefreshToken: @Model.RefreshToken
<br />
ExperiIn: @Model.ExperiIn
<br />
UserId: @Model.UserId
<br />
Scope: @Model.Scope
<br />
TokenType: @Model.TokenType
<br />

<form asp-controller="MercadoLibre" asp-action="Refresh" method="post">
    <input type="hidden" asp-for="RefreshToken" value="@Model.RefreshToken" />
    <button>Refresh Token</button>
    <a asp-controller="MercadoLibre" asp-action="UserInfo">User Info</a>
</form>

src/MercadoLibre.AspNetCore.TestServer/Views/MercadoLibre/Index.cshtml
@model MercadoLibre.AspNetCore.SDK.Models.AuthorizeToken

@{
    ViewData["Title"] = "Authentication Result";
}

AccessToken: @Model.AccessToken
<br />
RefreshToken: @Model.RefreshToken
<br />
ExperiIn: @Model.ExperiIn
<br />
UserId: @Model.UserId
<br />
Scope: @Model.Scope
<br />
TokenType: @Model.TokenType
<br />

src/MercadoLibre.AspNetCore.TestServer/Views/MercadoLibre/UserInfo.cshtml
@model MercadoLibre.AspNetCore.SDK.Models.Users.User

@{
    ViewData["Title"] = "User Info";
}

UserId: @Model.Id
<br />
FirstName: @Model.FirstName
<br />
LastName: @Model.LastName
<br />
Email: @Model.Email
<br />
<br />
---------------------------------------------------------------
<br />
<br />

@System.Text.Json.JsonSerializer.Serialize(Model, new System.Text.Json.JsonSerializerOptions()
{
    WriteIndented = true
})

src/MercadoLibre.AspNetCore.TestServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MercadoLibre.AspNetCore.TestServer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MercadoLibre.AspNetCore.TestServer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MercadoLibre" asp-action="Index">Mercado Libre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MercadoLibre.AspNetCore.TestServer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>